# Generated by Django 4.2.16 on 2024-12-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_league_league_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_teams', to='project.league'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
