# Generated by Django 4.2.16 on 2024-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_team_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
    ]
