# Generated by Django 4.2.16 on 2024-12-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_team_league_team_player_of_the_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.league'),
            preserve_default=False,
        ),
    ]
