# Generated by Django 4.2.16 on 2024-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
    ]
